#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Aug 11, 2021 04:48:48 PM EDT  platform: Windows NT

from sympy import *
from sympy.parsing.sympy_parser import parse_expr
import sympy as sp
import sys
import FourierSeries

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True


def set_Tk_var():
    global combobox
    combobox = tk.StringVar()
    global graphON
    graphON = tk.StringVar()

    global errorON
    errorON = tk.StringVar()

    global printON
    printON = tk.StringVar()

    global che45
    che45 = tk.IntVar()


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def runMethod(choiceSeries, fEntry, x0Entry, x1Entry, iterationsEntry, Scrolledtext1, checkError, checkGraph,
              checkPrint):
    Scrolledtext1.delete("1.0", 'end')
    k = choiceSeries.get()
    f = fEntry.get()
    x0 = N(parse_expr(x0Entry.get(), evaluate=False))
    x1 = N(parse_expr(x1Entry.get(), evaluate=False))

    iter_max = int(iterationsEntry.get())
    ops = ['Fourier sine series', 'Fourier cosine series', 'Fourier generalized series']
    if k == ops[0]:
        FourierSeries.sine_series(Scrolledtext1, f, x0, x1, niter=iter_max, parsefun=True,
                                  _error=checkError.get(), _graph=checkGraph.get(), _print=checkPrint.get())
    elif k == ops[1]:
        FourierSeries.cosine_series(Scrolledtext1, f, x0, x1, niter=iter_max, parsefun=True,
                                    _error=checkError.get(), _graph=checkGraph.get(), _print=checkPrint.get())
    elif k == ops[2]:
        FourierSeries.fourier_series(Scrolledtext1, f, x0, x1, niter=iter_max, parsefun=True,
                                     _error=checkError.get(), _graph=checkGraph.get(), _print=checkPrint.get())
    else:
        Scrolledtext1.insert(tk.INSERT, "Please pick a method")


if __name__ == '__main__':
    import FourierGUI_FINAL

    FourierGUI_FINAL.vp_start_gui()
